name: Refactor Report

on:
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Run ts-prune
        run: pnpm refactor:tsprune
      - name: Run depcruise
        run: pnpm refactor:depcruise
      - name: Collect aggregate
        run: pnpm refactor:collect
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: refactor-reports
          path: reports/*
